CREATE TABLE FRUTA (
cod_fruta INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
descripcion VARCHAR(60) NOT NULL,
calibre TINYINT NOT NULL,
categoria CHAR(1) NOT NULL,
origen VARCHAR(30) NOT NULL,
precio FLOAT(5,2) NOT NULL
);

CREATE TABLE PROVEEDOR (
    CIF CHAR(9) PRIMARY KEY,
    nombre_resp VARCHAR(30) NOT NULL,
    apellido_resp VARCHAR(45) NOT NULL,
    empresa VARCHAR(120) NOT NULL,
    email VARCHAR(60) NOT NULL,
    teléfono CHAR(9) NOT NULL,
    cod_postal SMALLINT NOT NULL
);

CREATE TABLE CLIENTE (
    ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE ALBARAN (
    cod_albaran INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    producto VARCHAR(60) NOT NULL,
    bulto INT NOT NULL,
    cajas INT NOT NULL,
    cod_prov CHAR(9) NOT NULL,
    fecha_entrada DATETIME NOT NULL,
    FOREIGN KEY (cod_prov) REFERENCES PROVEEDOR(CIF) ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE TABLE RECIBO (
    cod_recibo INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    detalle varchar(60) NOT NULL,
    cantidad INT NOT NULL,
    precio FLOAT(5,2) NOT NULL,
    fecha_compra DATETIME NOT NULL,
    cod_cliente BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (cod_cliente) REFERENCES CLIENTE(ID) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE FRU_ALB (
    cod_fruta INT UNSIGNED,
    cod_albaran INT UNSIGNED,
    PRIMARY KEY (cod_fruta,cod_albaran),
    FOREIGN KEY (cod_albaran) REFERENCES ALBARAN(cod_albaran) ON UPDATE CASCADE ON DELETE NO ACTION,
    FOREIGN KEY (cod_fruta) REFERENCES FRUTA(cod_fruta) ON UPDATE CASCADE ON DELETE NO ACTION
);

